import type { ChatSessionState } from '../types/chat-state';

export const INITIAL_STATE: ChatSessionState = {
  connectionStatus: 'disconnected',
  agentActivity: 'idle',
  statusLabel: 'Disconnected',
  statusDetail: 'Pi RPC process offline — configure and click Connect',
  modelInfo: null,
  availableModels: [],
  isModelsLoading: false,
  thinkingLevel: null,
  availableThinkingLevels: [],
  isChangingModel: false,
  sessionStats: null,
  modelStats: {},
  messages: [],
  hasMoreMessages: false,
  isLoadingOlderMessages: false,
  activeAssistantMessageId: null,
  pendingPromptId: null,
  lastError: null,
  sessionId: null,
  sessionFile: null,
  isHydrated: false,
  isResetting: false,
  sessions: [],
  isSessionsLoading: false,
  sessionsError: null,
  isSwitchingSession: false,
  isSidebarOpen: true,
  pendingApprovals: [],
};
